MyProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MyDigitalHealth/', include('MyDigitalHealth.urls')),
    path('', RedirectView.as_view(url='/MyDigitalHealth/')),  # just redirect everything to our app
]
#
# # Use static() to add url mapping to serve static files during development (only)
# from django.conf import settings
# from django.conf.urls.static import static
#
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


cardsort/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_package', views.create_package, name='create_package'),
    path('administration', views.package_administration, name='administration'),
    path('edit_package/<package_id>/', views.edit_package, name='edit_package'),
    path('package_open/<package_id>/', views.package_open, name='package_open'),
    path('assign/<base_package_id>/', views.assign_choose_user, name="assign"),
    path('assign_to/<base_package_id>/<user_id>/', views.assign_package_to_user, name='assign_to'),
    path('delete/<package_id>/', views.delete_package, name='delete'),
    path('save/<package_id>/', views.activity_save, name='save'),
    path('css/<package_id>', views.get_css, name='css'),
]

cardsort/models.py
from django.db import models
from django.contrib.auth.models import User


class Package(models.Model):
    package_name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    main_color = models.CharField(max_length=7, default='#337ab7')
    comments_enabled = models.BooleanField(default=True)
    type = "Base Package"

    def __str__(self):
        return self.package_name

    class Meta:
        verbose_name_plural = 'Packages'

    def get_categories(self):
        categories = Category.objects.filter(package=self)
        return categories

    def get_cards(self):
        cards = Card.objects.filter(package=self)
        return cards

    def to_dict(self):
        """ Used to return a package object as a dict, with package name, list of categories, and list of cards """
        list_of_category_objects = Category.objects.filter(package=self)
        list_of_card_objects = Card.objects.filter(package=self)

        package = {'package_id': self.pk,
                   'package_name': self.package_name,
                   'main_color': self.main_color,
                   'comments_enabled': self.comments_enabled,
                   'categories': list_of_category_objects,
                   'cards': list_of_card_objects,
                   }
        return package

    def assign(self):
        """ Method to duplicate the package as an AssignedPackage """
        assigned_package = AssignedPackage(package_name=self.package_name, owner=self.owner, main_color=self.main_color,
                                           comments_enabled=self.comments_enabled)
        assigned_package.save()
        # Base Packages have no blank "Cards" default category, so we need to add it here
        first_category = Category(category_name="Cards", package=assigned_package)
        first_category.save()
        for category in self.get_categories():
            new_category = Category(category_name=category.category_name, package=assigned_package)
            new_category.save()
        for card in self.get_cards():
            # Assign all cards to the default first_category
            new_card = Card(card_text=card.card_text, package=assigned_package, category=first_category)
            new_card.save()
        return assigned_package


class AssignedPackage(Package):
    """ Represents a Package in a state where it is owned by a user """
    comment_text = models.TextField(default='')
    type = "Assigned Package"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.type = "Assigned Package"

    class Meta:
        verbose_name_plural = 'Assigned Packages'

    def __str__(self):
        return "%s assigned to user" % self.package_name

    def to_dict(self):
        """ Used to return a saved package object as a dict for easy context rendering """
        assigned_package = {'package_id': self.pk,
                            'package_name': self.package_name,
                            'main_color': self.main_color,
                            'comments_enabled': self.comments_enabled,
                            'categories': self.get_categories(),
                            'cards': self.get_cards(),
                            'comment': self.comment_text
                            }
        return assigned_package


class Category(models.Model):
    """ Represents a category within a package into which Cards are sorted """
    category_name = models.CharField(max_length=200)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'

    def get_cards(self):
        cards = Card.objects.filter(category=self)
        return cards


class Card(models.Model):
    """ Represents a card within a package which is sorted into a category"""
    card_text = models.CharField(max_length=200)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.card_text

    class Meta:
        verbose_name_plural = 'Cards'


class UserSavedPackage(models.Model):
    """ Represents the instance of a package as assigned to a user """
    base_package = models.ForeignKey(Package, on_delete=models.CASCADE, related_name="base_package")
    assigned_package = models.ForeignKey(Package, on_delete=models.CASCADE, related_name="user_package")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Saved Packages'

    def __str__(self):
        return "Saved package %s for %s" % (self.assigned_package, self.user)

cardsort/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from cardsort.forms import PackageForm
from cardsort.models import Package, UserSavedPackage, Card, AssignedPackage


def create_package(request):
    """ Administrator functionality to create new Packages with related Cards and Categories """
    if request.method == 'POST':
        form = PackageForm(request=request)
        if form.is_valid():
            form.save_data()
            messages.info(request, 'Save successful')
        else:
            messages.error(request, 'Package could not be saved - form not valid')  # send an error here as required
        return HttpResponseRedirect('administration')
    else:
        kwargs = {'num_categories': 3, 'num_cards': 3}
        form = PackageForm(**kwargs).to_dict()
        return render(
            request,
            'create_edit.html',
            context=form
        )


def edit_package(request, package_id):
    """ Display the editing page with pre-filled data; if POST, save the edited package and redirect to admin page """
    if request.method == 'POST':
        form = PackageForm(request=request)
        if form.is_valid():
            form.save_data()
            messages.info(request, 'Save successful')
        else:
            messages.error(request, "An error occurred when saving")
        return redirect('administration')
    else:
        filled_form = PackageForm(package_id=package_id).to_dict()
        return render(
            request,
            'create_edit.html',
            context=filled_form
        )


@staff_member_required(None, redirect_field_name='next', login_url='login')
def package_administration(request):
    """ Generate and display the Administration page with a list of the packages the admin has created """
    own_packages = Package.objects.filter(owner=request.user, assignedpackage__isnull=True)
    context = {'own_packages': own_packages}
    return render(
        request,
        'package_administration.html',
        context
    )


def package_open(request, package_id):
    """ Display the package as a cardsort activity for the user to complete """
    if UserSavedPackage.objects.filter(base_package=package_id, user=request.user).exists():
        user_save = UserSavedPackage.objects.get(base_package=package_id, user=request.user)
        assigned_package = AssignedPackage.objects.get(pk=user_save.assigned_package.pk)
        context = assigned_package.to_dict()
        return render(
            request,
            'active.html',
            context
        )
    else:
        messages.error(request, "Sorry, this package is not assigned to this user")
        return render(
            request,
            'index.html',
        )


def activity_save(request, package_id):
    """ Save card > category associations and user comment in the database """
    if request.method == "POST":
        data = request.POST
        package = AssignedPackage.objects.get(pk=package_id)
        for category in package.get_categories():
            assigned_cards = data['card_ids_for_' + str(category.pk)].split(',')
            for card_id in assigned_cards:
                if not card_id == "":
                    card = Card.objects.get(pk=int(card_id))
                    card.category = category
                    card.save_data()
        user_save = UserSavedPackage.objects.get(assigned_package=package)
        package.comment_text = data['comment']
        package.save_data()
        user_save.save_data()
        messages.info(request, "Sort saved successfully!")
    return redirect('home')


@staff_member_required(None, redirect_field_name='next', login_url='login')
def assign_choose_user(request, base_package_id):
    base_package = Package.objects.get(pk=base_package_id)
    user_list = User.objects.all()
    context = {'base_package': base_package,
               'user_list': user_list
               }
    return render(
        request,
        'assign_package.html',
        context
    )


@staff_member_required(None, redirect_field_name='next', login_url='login')
def assign_package_to_user(request, base_package_id, user_id):
    """ Function to assign the active package to the provided user"""
    base_package = Package.objects.get(pk=base_package_id)
    assigned_user = User.objects.get(pk=user_id)
    if UserSavedPackage.objects.filter(base_package=base_package, user=assigned_user).exists():
        messages.info(request, "This package is already assigned to this user")
        return redirect('assign', base_package_id)
    else:
        # TODO Move to base_package.assign(user_id) and remove 'UserSavedPackage'
        # Duplicate the Package, Categories, and Cards, so they are for this user only
        new_package = base_package.assign()
        assignment = UserSavedPackage(base_package=base_package, assigned_package=new_package, user=assigned_user)
        assignment.save()
        messages.info(request, "Package successfully assigned to user")
        return redirect('assign', base_package_id)


@staff_member_required(None, redirect_field_name='next', login_url='login')
def delete_package(request, package_id):
    # TODO: try/catch errors here
    instance = Package.objects.get(pk=package_id)
    instance.delete()
    messages.info(request, "Package deleted")
    return redirect('administration')


def get_css(request, package_id):
    package = Package.objects.get(pk=package_id)
    main_color = package.main_color
    return render(
        request,
        'colors.css',
        {'main_color': main_color},
        content_type='text/css'
    )

cardsort/templates/active.html
{% extends "base_generic.html" %}

{% block heading %}
    <h1>{{ package_name }}</h1>
{% endblock %}
{% block content %}
    {% load static %}
    <script src="{% static 'cardsort.js' %}"></script>
    <link href="{% url "css" package_id %}" rel="stylesheet" />
    <div class="container">
        <form class="form" method="post" action="{% url 'save' package_id %}" onsubmit="return processCards()">
            {% csrf_token %}
        {% for category in categories %}
        <div class="cards">
            <h3 class="list-group-item active">{{ category.category_name }}</h3>
            <ul class="list-group connection">
                <input type="hidden" id="category_{{ category.pk }}" name="card_ids_for_{{ category.pk }}"/>
                {% for card in cards %}
                    {% if card.category.pk == category.pk %}
                    <li class="list-group-item" id="{{ card.pk }}">{{ card.card_text }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
        <div class="row form-group">
            <input id ="id_package_id" type="hidden" name="package_id" value="{{ package_id}}">
            {% if comments_enabled %}
                <textarea class="form-control" id="id_comment_text" name="comment"
                          placeholder="Feel free to add any comments">{{ comment }}</textarea><br>
            {% endif %}
            <input type="submit" value="Save" class="btn btn-default"/>
            <a href="{% url 'index' %}" class="btn btn-default">Close</a>
        </div>
        </form>
    </div>
{% endblock %}

cardsort/templates/create.html
{% extends "base_generic.html" %}
{% block heading %}
    <h1>Create A New Package</h1>
{% endblock %}
{% block content %}
    {% load static %}
    <script src="{% static 'cardsort.js' %}"></script>
    <div>
    {% if exists_flag %}
    <form action="{% url 'edit_save' package_id %}" method="post" id="new_package">
    {% else %}
    <form action="{% url 'create_package' %}" method="post" id="new_package">
    {% endif %}
        {% csrf_token %}
        <div class="form-row" id="form_items">
            <div id="id_package_name">
                {{ package_form }}
            </div>
            <div class="col-sm-7">
                <h2 class="form-signin-heading">Cards</h2>
                {{ cards_formset.management_form }}
                    <ul id="id_card_list">
                        {% for card_form in cards_formset %}
                            <li>{{ card_form }}<button type="button" class="btn btn-default">Remove</button></li>
                        {% endfor %}
                    </ul>
                <input type="button" value="Add Another Card" class="btn btn-default" onclick="cloneItem('card')"/>
            </div>
            <div class="col-sm-5">
                <h2 class="form-signin-heading">Categories</h2>
                {{ categories_formset.management_form }}
                <ul id="id_category_list">
                    {%  for category in categories_formset %}
                        <li>{{ category }}<button type="button" class="btn btn-default">Remove</button></li>
                    {% endfor %}
                </ul>
            <input type="button" value="Add A Category" class="btn btn-default" onclick="cloneItem('category')"/>
            </div>
        </div>
        <div class="row" id="buttons">
            <input type="submit" value="Save and Close" class="btn btn-default"/>
        </div>
    </form>
    </div>
{% endblock %}

cardsort/templates/create_edit.html
{% extends "base_generic.html" %}
{% block heading %}
    <h1>Create A New Package</h1>
{% endblock %}
{% block content %}
    {% load static %}
    <script src="{% static 'cardsort.js' %}"></script>
    <div>
    {% if package_id == -1 %}
        <form action="{% url 'create_package' %}" method="post" id="new_package">
    {% else %}
        <form action="{% url 'edit_package' package_id %}" method="post" id="new_package">
    {% endif %}
        {% csrf_token %}
        <div class="form-row" id="form_items">
            <div id="id_package_name">
                {{ package_base_form }}
            </div>
            <div class="col-sm-7">
                <h2 class="form-signin-heading">Cards</h2>
                {{ cards_formset.management_form }}
                    <ul id="id_card_list">
                        {% for card_form in cards_formset %}
                            <li>{{ card_form }}<a href="" class="btn btn-default">Remove</a></li>
                        {% endfor %}
                    </ul>
                <input type="button" value="Add Another Card" class="btn btn-default" onclick="cloneItem('card')"/>
            </div>
            <div class="col-sm-5">
                <h2 class="form-signin-heading">Categories</h2>
                {{ categories_formset.management_form }}
                <ul id="id_category_list">
                    {%  for category in categories_formset %}
                        <li>{{ category }}<a href="" class="btn btn-default">Remove</a></li>
                    {% endfor %}
                </ul>
            <input type="button" value="Add A Category" class="btn btn-default" onclick="cloneItem('category')"/>
            </div>
        </div>
        <div class="row" id="buttons">
            {% if package_id %}
            <input id ="id_package_id" type="hidden" name="package_id" value="{{ package_id }}"/>
            {% endif %}
            <input type="submit" value="Save and Close" class="btn btn-default"/>
            <a href="{% url "administration" %}" class="btn btn-default">Close</a>
        </div>
    </form>
    </div>
{% endblock %}